### ISSUE TITLE
Pack and unpack with real folders

### ISSUE THREAD

**Issue by JPMeehan** [MetaMorphic-Digital/draw-steel#41]
The current pack/unpack setup has a flat structure and only implements folders inside foundry. While this is functional, it would be even better if content was packed and unpacked according to its actual folder.

**Comment by JPMeehan** [comment]
Accidentally did a direct push to main. Need to revisit branch protection rules; @krbz999 could you check the commit and provide any feedback?

**Comment by krbz999** [comment]
> Accidentally did a direct push to main. Need to revisit branch protection rules; @krbz999 could you check the commit and provide any feedback?

I think it's good, though I'm not sure I'm fond of prefacing with the document subtype. We should also consider folder support.

**Comment by JPMeehan** [comment]
The unpack operation also handles folders. The reason I like the document name prefacing is at least in my 5e modules makes it a lot easier to sort through mixed content — all the folders get organized together, for example.

**Comment by JPMeehan** [comment]
How about I repurpose this issue to that, since our journal compendium shouldn't need internal folders

**Comment by Taroc0** [comment]
I looked into this. While `compilePack()` has a `recursive` option to also compile all json files from subfolders, there is no such option for `extractPack()`. So unpacking would create a flat structure without any subfolders even so the ldb files are in subfolders. Any ideas how to fix that?

**Comment by krbz999** [comment]
> I looked into this. While `compilePack()` has a `recursive` option to also compile all json files from subfolders, there is no such option for `extractPack()`. So unpacking would create a flat structure without any subfolders even so the ldb files are in subfolders. Any ideas how to fix that?

Loop once to determine the folder structure, then on second loop set the file name using this folder structure.

**Comment by Taroc0** [comment]
Thanks, that approach was too obvious ;) I did it that way and faced another problem.

I set up a folder structure like this for testing:

- src/packs
  - journals
    - combat
      - journal_conditions_\<id\>.json
    - system_info
      - journal_System_info_\<id\>.json
    - journal_Backer_Packet_\<id\>.json

So two journal files are in subfolders and the Backer_Packet journal is not.
The `pullJSONtoLDB` maintains this folder structure. The json files are correctly compiled to ldb-files (and the other files 000004.log, MANIFEST-000002 ...) correctly:

- packs
  - journals
    - combat
      - 000005.ldb
    - system_info
      - 000005.ldb
    - 000005.ldb

I checked that `combat/000005.ldb` and `system_info/000005.ldb` are not empty and do contain the journal text. However, Foundry only shows the Backer Packet journal inside the "System Journals" compedium. The Conditions and System Info journal are gone. I think this is because Foundry doesn't read any subfolders from the file system. Foundry just takes the top level ldb-file `packs/journals/000005.ldb`. So it looks like, we have to compile all journal json files into one journal ldb file and find a way to restore the folder structure during the unpack process somehow. But I can't see how that could work.

So the other option would be to have corresponding folders inside the Journals compendium and use that internal folder structure to build the file system folder structure for the source files with the unpack script.

Am I missing a more straight forward and obvious approach again?
